#PBS -S /bin/bash
#PBS -l walltime=24:00:00
#PBS -l mem=8gb
#PBS -e logs/run_${TISSUE}.err
#PBS -o logs/run_${TISSUE}.out


source ~/.bash_profile
source ~/.bashrc
cd ${PBS_O_WORKDIR}

conda activate pytorch-1.4.0-cpu_py37

SNMK=/gpfs/data/im-lab/nas40t2/yanyul/softwares/miniconda2/envs/mixqtl/bin/snakemake

$SNMK -s mixqtl.snmk --configfile config.00.yaml -p \
  --config tissue=$TISSUE --cores ${NCORE} > ${PBS_O_WORKDIR}/logs/run_${TISSUE}.log 2>&1
  
