#PBS -S /bin/bash
#PBS -l walltime=24:00:00
#PBS -l mem=4gb
#PBS -e zenodo_meta/upload_${BATCH}.err
#PBS -o zenodo_meta/upload_${BATCH}.out

source ~/.bash_profile
source ~/.bashrc
cd ${PBS_O_WORKDIR}

conda activate zenodo


for tt in `cat zenodo_meta/batch$BATCH`
do
  
  if [[ ! -z $WITHID ]]
  then
    tt=`echo $tt | tr ',' '\n' | head -n 1`
    myid=`echo $tt | tr ',' '\n' | head -n 2` 
  fi
  tissue_list=zenodo_meta/filelist_$tt.txt
  
  for i in `seq 1 22`
  do
    echo /scratch/t.cri.yliang/mixQTL-GTExV8/mixqtl_cleanup/mixqtl.$tt.chr$i.parquet >> $tissue_list
  done
  
  if [[ -z $myid ]]
  then
    python /gpfs/data/im-lab/nas40t2/yanyul/GitHub/misc-tools/zenodo_upload/zenodo_uploader.py \
      --meta-yaml zenodo_meta/$tt.yaml \
      --file-list $tissue_list \
      --token /home/t.cri.yliang/zenodo_haky.txt > zenodo_meta/upload_${tt}.log 2>&1
  else
    python /gpfs/data/im-lab/nas40t2/yanyul/GitHub/misc-tools/zenodo_upload/zenodo_uploader.py \
      --depository $myid \
      --file-list $tissue_list \
      --token /home/t.cri.yliang/zenodo_haky.txt > zenodo_meta/upload_${tt}.log 2>&1
  fi
  rm $tissue_list

done
