if 'outdir' in config:
    config['outdir'] = 'output'

if '{chr_num}' in config['eqtl_table']:
    rule all:
        input:
            [ '{outdir}/signif_qtl.{name_tag}.chr{chr_num}_x_{tissue}.parquet'.format(chr_num=i, **config) for i in range(1, 23) ]
else:
    rule all:
        input:
            '{outdir}/signif_qtl.{name_tag}_x_{tissue}.parquet'.format(**config)

rule run:
    input:
        config['eqtl_table']
    output:
        '{outdir}/signif_qtl.{name_tag}_x_{tissue}.parquet'
    shell:
        'python extract_signif_eqtl.py \
            --input {input[0]} \
            --fdr-cutoff {config[fdr_cutoff]} \
            --mode {config[mode]} \
            --tensorqtl {config[tensorqtl_code_path]} \
            --output {output[0]}'

rule run_by_chr:
    input:
        config['eqtl_table']
    output:
        '{outdir}/signif_qtl.{name_tag}.chr{chr_num}.parquet'
    shell:
        'python extract_signif_eqtl.py \
            --input {input[0]} \
            --fdr-cutoff {config[fdr_cutoff]} \
            --mode {config[mode]} \
            --tensorqtl {config[tensorqtl_code_path]} \
            --output {output[0]}'