# nfactor: 60
outdir: '/scratch/t.cri.yliang/mixQTL-GTExV8/preprocessing/peer'
# tissue: 'Whole_Blood'
covariate: '/gpfs/data/gtex-group/v8/59349/gtex/exchange/GTEx_phs000424/exchange/analysis_releases/GTEx_Analysis_2017-06-05_v8/eqtl/GTEx_Analysis_v8_eQTL_covariates/{tissue}.v8.covariates.txt'
expr_mat: '/scratch/t.cri.yliang/mixQTL-GTExV8/preprocessing/expression/merge-{tissue}.rds'
path_to_peertool: '/gpfs/data/im-lab/nas40t2/yanyul/softwares/peer/bin/peertool'

