outdir: '/scratch/t.cri.yliang/mixQTL-GTExV8/mixqtl'

hap_pattern: '/scratch/t.cri.yliang/gtexv8_genotype_in_parquet/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.SHAPEIT2_phased.MAF01.chr{{chr_num}}.hap{hap_num}.parquet'

library_size: 
  path: '/scratch/t.cri.yliang/mixQTL-GTExV8/preprocessing/prepare_data/{tissue}/gtex_v8_library_size.txt.gz'
  sample_id_col: 'SAMPID'
  libsize_col: 'SMMPPD'

covariate_pattern: '/scratch/t.cri.yliang/mixQTL-GTExV8/preprocessing/prepare_data/{tissue}/covariates.txt.gz'

asc: 
  pattern: '/scratch/t.cri.yliang/mixQTL-GTExV8/preprocessing/prepare_data/{{tissue}}/allele_specific_count.hap{hap_num}.txt.gz'
  gene_col: 'GENE_ID'

trc_pattern: '/scratch/t.cri.yliang/mixQTL-GTExV8/preprocessing/prepare_data/{tissue}/total_count.bed.gz'

egene: 
  pattern: '/gpfs/data/gtex-group/v8/59349/gtex/exchange/GTEx_phs000424/exchange/analysis_releases/GTEx_Analysis_2017-06-05_v8/eqtl/GTEx_Analysis_v8_eQTL/{tissue}.v8.egenes.txt.gz'
  gene_col: 'gene_id'

count_data_rds: '/scratch/t.cri.yliang/mixQTL-GTExV8/preprocessing/expression/merge-{tissue}.rds'

tensorqtl_param_yaml: 'tensorqtl_param.yaml'
nthread: 8
tensorqtl_dir: '/gpfs/data/im-lab/nas40t2/yanyul/GitHub/tensorqtl/tensorqtl'
run_script_path: '/gpfs/data/im-lab/nas40t2/yanyul/GitHub/mixqtl-pipeline/misc_scripts/prepare_data_for_py_mixqtl_runs/run_py_mixqtl.py'

